# Generated by Django 5.2.8 on 2025-11-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_id_alter_booking_no_of_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_guest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.IntegerField(),
        ),
    ]
